### ISSUE TITLE
Error when running local steemit.com instance

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#1019]
I have been working on a local instance of steemit.com, and I recently just refreshed my branch with the latest master. Since the update, I have not been able to get steemit to run. I have also tried deleting the entire steemit.com directory and doing a fresh git clone, although it results in the same error. Have you seen this before?

 npm start

> Steemit.com@1.0.0 start /home/steemit3/steemit.com
> babel-node ./webpack/dev-server.js

`webpack-dev-server` listening on port 3001
updated webpack-stats-dev.json
Hash: 7c1799a8a33ae18698ec
Version: webpack 1.13.2
Time: 32419ms
                               Asset       Size  Chunks             Chunk Names
1fe805bf4c773eeb3bebf1e78e6736ed.jpg    15.2 kB          [emitted]
0ee064e31a180b13aca01418634567a1.png    4.74 kB          [emitted]
           0.7c1799a8a33ae18698ec.js     209 kB    0, 1  [emitted]  IntlBundle
                           vendor.js    25.8 kB       1  [emitted]  vendor
         app.7c1799a8a33ae18698ec.js    8.21 MB    2, 1  [emitted]  app
        app-82a01073d41bdc5b1cff.css     147 kB    2, 1  [emitted]  app
       0.7c1799a8a33ae18698ec.js.map     239 kB    0, 1  [emitted]  IntlBundle
                       vendor.js.map    26.7 kB       1  [emitted]  vendor
     app.7c1799a8a33ae18698ec.js.map    9.37 MB    2, 1  [emitted]  app
    app-82a01073d41bdc5b1cff.css.map  105 bytes    2, 1  [emitted]  app
Child extract-text-webpack-plugin:
                                   Asset     Size  Chunks       Chunk Names
    1fe805bf4c773eeb3bebf1e78e6736ed.jpg  15.2 kB
webpack built 7c1799a8a33ae18698ec in 32419ms
Time: 32419ms
                               Asset       Size  Chunks             Chunk Names
1fe805bf4c773eeb3bebf1e78e6736ed.jpg    15.2 kB          [emitted]
0ee064e31a180b13aca01418634567a1.png    4.74 kB          [emitted]
           0.7c1799a8a33ae18698ec.js     209 kB    0, 1  [emitted]  IntlBundle
                           vendor.js    25.8 kB       1  [emitted]  vendor
         app.7c1799a8a33ae18698ec.js    8.21 MB    2, 1  [emitted]  app
        app-82a01073d41bdc5b1cff.css     147 kB    2, 1  [emitted]  app
       0.7c1799a8a33ae18698ec.js.map     239 kB    0, 1  [emitted]  IntlBundle
                       vendor.js.map    26.7 kB       1  [emitted]  vendor
     app.7c1799a8a33ae18698ec.js.map    9.37 MB    2, 1  [emitted]  app
    app-82a01073d41bdc5b1cff.css.map  105 bytes    2, 1  [emitted]  app
Child extract-text-webpack-plugin:
                                   Asset     Size  Chunks       Chunk Names
    1fe805bf4c773eeb3bebf1e78e6736ed.jpg  15.2 kB
webpack: bundle is now VALID.
connecting to wss://node.steem.ws
Application started on port 3002
type `rs` in console for restarting koa application

**Once it gets here, it just sits at the console. When I try to connect via the browser, it says "Internal Server Error" and throws this error in the command window:**

Error
    at _free_and_throw_error (/home/steemit3/steemit.com/node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:378:15)
    at Object.crypto_secretbox_open_easy (/home/steemit3/steemit.com/node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:2735:3)
    at decrypt (/home/steemit3/steemit.com/node_modules/@steem/crypto-session/index.js:90:19)
    at Object.decode (/home/steemit3/steemit.com/node_modules/@steem/crypto-session/index.js:48:22)
    at Object.session (/home/steemit3/steemit.com/node_modules/koa-session/index.js:74:24)
    at Object.flash (/home/steemit3/steemit.com/node_modules/koa-flash/index.js:18:13)
    at next (native)
    at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-route/index.js:27:49)
    at next (native)
    at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-route/index.js:39:21)
    at next (native)
    at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-route/index.js:39:21)
    at next (native)
    at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-compose/index.js:28:19)
    at next (native)
    at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-session/index.js:116:14)
    at next (native)
    at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-compose/index.js:28:19)
    at next (native)
    at onFulfilled (/home/steemit3/steemit.com/node_modules/co/index.js:65:19)
    at /home/steemit3/steemit.com/node_modules/co/index.js:54:5
    at Object.co (/home/steemit3/steemit.com/node_modules/co/index.js:50:10)
    at Object.createPromise (/home/steemit3/steemit.com/node_modules/co/index.js:30:15)
    at Server.<anonymous> (/home/steemit3/steemit.com/node_modules/koa/lib/application.js:136:8)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

  Error: @steem/crypto-session: Discarding session: bBssaM85071uCa6+gEb0U9byHg6hIkCpn5YwGXQLo9s1jwYAtZaineUdluo+//N7SSrpqGwBk4eVj/kFGG5jrmZzuWsVFrvPEvEbG28j94upgYcxJB+CZJw2orox/WiGtQWyli5d6d9t4CaWPnMFGsNH+Wf9GwDB7M0LLliMHokm2iN5BVySsXXZK5BP/FouMi8F/r5/6orlAUaL2BmvF3jKWXy/sfjckPvJE58U56EalWe2fF08nSuVCjjshABiCQ9B6DWfgB2IUiCwJquYI/juuVUN2CVk9djuwFOREVfyvZuVWxNbRAcTA14iHdvq30rqG0GWEyslUBje
      at Object.decode (/home/steemit3/steemit.com/node_modules/@steem/crypto-session/index.js:65:19)
      at Object.session (/home/steemit3/steemit.com/node_modules/koa-session/index.js:74:24)
      at Object.flash (/home/steemit3/steemit.com/node_modules/koa-flash/index.js:18:13)
      at next (native)
      at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-route/index.js:27:49)
      at next (native)
      at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-route/index.js:39:21)
      at next (native)
      at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-route/index.js:39:21)
      at next (native)
      at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-compose/index.js:28:19)
      at next (native)
      at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-session/index.js:116:14)
      at next (native)
      at Object.<anonymous> (/home/steemit3/steemit.com/node_modules/koa-compose/index.js:28:19)
      at next (native)
      at onFulfilled (/home/steemit3/steemit.com/node_modules/co/index.js:65:19)
      at /home/steemit3/steemit.com/node_modules/co/index.js:54:5
      at Object.co (/home/steemit3/steemit.com/node_modules/co/index.js:50:10)
      at Object.createPromise (/home/steemit3/steemit.com/node_modules/co/index.js:30:15)
      at Server.<anonymous> (/home/steemit3/steemit.com/node_modules/koa/lib/application.js:136:8)
      at emitTwo (events.js:106:13)
      at Server.emit (events.js:191:7)
      at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

**After that, it just keeps looping with this:**

WARNING! ws connection wss://node.steem.ws closed:  Connection dropped by remote peer.
WebSocket: will try to reconnect in 1 sec, attempt #1
connecting to wss://node.steem.ws

**Comment by roadscape** [comment]
Ideally this would be handled more gracefully. You should try clearing your cookies/localStorage for localhost:3002

**Comment by TimCliff** [comment]
Ok, thanks! I will try this out tonight and let you know if it works.

**Comment by TimCliff** [comment]
It works! Thanks again :)
