### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by gulfpearl** [steemit/steemit.com#833]
npm run build gives me the following error:
 ```
10 verbose lifecycle Steemit.com@1.0.0~build: CWD: /root/steemit.com
11 silly lifecycle Steemit.com@1.0.0~build: Args: [ '-c',
11 silly lifecycle   'NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js' ]
12 silly lifecycle Steemit.com@1.0.0~build: Returned: code: 137  signal: null
13 info lifecycle Steemit.com@1.0.0~build: Failed to exec build script
14 verbose stack Error: Steemit.com@1.0.0 build: `NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js`
14 verbose stack Exit status 137
14 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.9.2/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.9.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Steemit.com@1.0.0
16 verbose cwd /root/steemit.com
17 error Linux 4.4.0-45-generic
18 error argv "/root/.nvm/versions/node/v6.9.2/bin/node" "/root/.nvm/versions/node/v6.9.2/bin/npm" "run" "build"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error Steemit.com@1.0.0 build: `NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js`
22 error Exit status 137
23 error Failed at the Steemit.com@1.0.0 build script 'NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Steemit.com package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Steemit.com
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Steemit.com
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by roadscape** [comment]
How much RAM does your machine have?

**Comment by gulfpearl** [comment]
16GB on an aws EC2 instance, Ubuntu.

**Comment by roadscape** [comment]
Does `npm start` work?

**Comment by gulfpearl** [comment]
I don't know what I did since I've tried so many npm flags and configuration changes, but its working now on production. 

I'll try to figure out what went wrong tomorrow and let you know.
